ik_walk:
    ros__parameters:
        # servo p_gain
        p_gain: 16
        #
        # Robot model
        #
        # Model leg typical length between
        # each rotation axis in meters
        dist_hip_to_knee: 0.1415
        dist_knee_to_ankle: 0.1415
        dist_ankle_to_ground: 0.059
        #
        # Distance between the two feet in lateral
        # axis while in zero position
        dist_feet_lateral: 0.075
        #
        # Walk egine
        #
        # walk controll parameter
        step_gain: 0.0
        lateral_gain: 0.0
        turn_gain: 0.0
        #
        # Complete (two legs) walk cycle frequency
        # in Hertz
        freq: 1.9
        #
        # Global gain multiplying all time
        # dependant movement between 0 and 1.
        # Control walk enabled/disabled smoothing.
        # 0 is walk disabled.
        # 1 is walk fully enabled
        enabled_gain: 1.0
        #
        # Length of double support phase
        # in phase time
        # (between 0 and 1)
        # 0 is null double support and full single support
        # 1 is full double support and null single support
        support_phase_ratio: 0.0
        #
        # Lateral offset on default foot
        # position in meters (foot lateral distance)
        # 0 is default
        # > 0 is both feet external offset
        foot_y_offset: 0.026
        #
        # Forward length of each foot step in meters
        # >0 goes forward
        # <0 goes backward
        # (dynamic parameter)
        step_gain: 0.0
        #
        # Vertical rise height of each foot
        # in meters (positive)
        rise_gain: 0.04        
        #
        # Angular yaw rotation of each
        # foot for each step in radian.
        # 0 does not turn
        # >0 turns left
        # <0 turns right
        # (dynamic parameter)
        turn_gain: 0.0
        #
        # Lateral length of each foot step
        # in meters.
        # >0 goes left
        # <0 goes right
        # (dynamic parameter)
        lateral_gain: 0.0
        #
        # Vertical foot offset from trunk
        # in meters (positive)
        # 0 is in init position
        # > 0 set the robot lower to the ground
        trunk_z_offset: 0.02
        #
        # Lateral trunk oscillation amplitude
        # in meters (positive)
        swing_gain: 0.04
        #
        # Lateral angular oscillation amplitude
        # of swing trunkRoll in radian
        swing_roll_gain: 0.0
        #
        # Phase shift of lateral trunk oscillation
        # between 0 and 1
        swing_phase: 0.25
        #
        # Foot X-Z spline velocities
        # at ground take off and ground landing.
        # Step stands for X and rise stands for Z velocities.
        # Typical values ranges within 0 and 5.
        # >0 for DownVel is having the foot touching the
        # ground with backward velocity.
        # >0 for UpVel is having the foot going back
        #  forward with non perpendicular tangent.
        step_up_vel: 4.0
        step_down_vel: 4.0
        rise_up_vel: 4.0
        rise_down_vel: 4.0
        #
        # Time length in phase time
        # where swing lateral oscillation
        # remains on the same side
        # between 0 and 0.5
        swing_pause: 0.0
        #
        # Swing lateral spline velocity (positive).
        # Control the "smoothness" of swing trajectory.
        # Typical values are between 0 and 5.
        swing_vel: 4.0
        #
        # Forward trunk-foot offset
        # with respect to foot in meters
        # >0 moves the trunk forward
        # <0 moves the trunk backward
        trunk_x_offset: 0.02
        #
        # Lateral offset on default foot
        # position in meters (foot lateral distance)
        # 0 is default
        # > 0 is both feet external offset
        foot_y_offset: 0.01
        #
        # Trunk angular rotation
        # around Y in radian
        # >0 bends the trunk forward
        # <0 bends the trunk backward
        trunk_pitch: -0.05
        #
        # Trunk angular rotation
        # around X in radian
        # >0 bends the trunk on the right
        # <0 bends the trunk on the left
        trunk_roll: 0.0
        # 
        # Add extra offset on X, Y and Z
        # direction on left and right feet
        # in meters
        # (Can be used for example to implement
        # dynamic kick)
        extra_left_x: 0.0
        extra_left_y: 0.0
        extra_left_z: 0.0
        extra_right_x: 0.0
        extra_right_y: 0.0
        extra_right_z: 0.0
        #
        # Add extra angular offset on
        # Yaw, Pitch and Roll rotation of
        # left and right foot in radians
        extra_left_yaw: 0.0
        extra_left_pitch: 0.0
        extra_left_roll: 0.0
        extra_right_yaw: 0.0
        extra_right_pitch: 0.0
        extra_right_roll: 0.0